# Переменные по умолчанию
#
seaf2drawio:
  # Можно указывать как отдельные файлы, так и директории (будут загружены все .yaml/.yml файлы)
  data_yaml_file: 
    - data/example/
  drawio_pattern: data/base.drawio
  #  drawio_pattern: data/base_for_example.drawio
  output_file: result/Sample_graph.drawio
  verify_generation: true
#  link_style: straight  # опционально: устанавливает прямые связи вместо угловых

drawio2seaf:
  schema_file: data/seaf_schema.yaml
  drawio_file: result/Sample_graph.drawio
  output_file: result/seaf.yaml