# Переменные по умолчанию
#
seaf2drawio:
  data_yaml_file:
  - data/example/test_seaf_ta_P41_v0.12.yaml
  - data/example/components_network_dc01.yaml
  #- data/example/systems.yaml
  #- data/example/enablers.yaml
  drawio_pattern: data/base.drawio
  output_file: result/Sample_graph.drawio

drawio2seaf:
  schema_file: data/seaf_schema.yaml
  drawio_file: result/Sample_graph.drawio
  output_file: result/seaf.yaml
